//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManageSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class associatecardinfo
    {
        public string AssociateCardId { get; set; }
        public string CardHolder { get; set; }
        public System.DateTime TradeTime { get; set; }
        public string TradeType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string OilProduct { get; set; }
        public Nullable<double> Count { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<double> BonusPoints { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Place { get; set; }
        public string guid { get; set; }
    }
}
