//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManageSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class returnregister
    {
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public string ReturnPlace { get; set; }
        public string ReturnDetail { get; set; }
        public string user { get; set; }
        public Nullable<double> TravelMileage { get; set; }
        public Nullable<int> CarRepair { get; set; }
        public string RepairDetail { get; set; }
        public string CarNumber { get; set; }
        public string UniqueCode { get; set; }
        public Nullable<int> ReturnState { get; set; }
    }
}
