//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManageSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class carcostregister
    {
        public Nullable<int> Type { get; set; }
        public string CarNumber { get; set; }
        public string AccessUser { get; set; }
        public string UseTime { get; set; }
        public string Code { get; set; }
        public string Table { get; set; }
        public Nullable<System.DateTime> MaintenanceStartDate { get; set; }
        public Nullable<System.DateTime> MaintenanceEndDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Id { get; set; }
    }
}
