//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManageSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class carinfo
    {
        public string CarBrand { get; set; }
        public string CarNumber { get; set; }
        public string CarModel { get; set; }
        public string EngineNumber { get; set; }
        public string CarType { get; set; }
        public Nullable<decimal> CarPrice { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<System.DateTime> InsuranceStartDate { get; set; }
        public Nullable<System.DateTime> InsuranceEndDate { get; set; }
        public Nullable<System.DateTime> AnnualStartDate { get; set; }
        public Nullable<System.DateTime> AnnualEndDate { get; set; }
        public Nullable<System.DateTime> MaintenanceStartDate { get; set; }
        public Nullable<System.DateTime> MaintenanceEndDate { get; set; }
        public string Mileage { get; set; }
        public string CarPhoto { get; set; }
        public Nullable<int> NeedMaintain { get; set; }
        public Nullable<int> CarState { get; set; }
        public Nullable<int> CarStateDetial { get; set; }
        public Nullable<System.DateTime> HolodayStart { get; set; }
        public Nullable<System.DateTime> HolodayEnd { get; set; }
        public string LoginAdmin { get; set; }
        public string MaintainUser { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> IsOut { get; set; }
        public string CarPassword { get; set; }
        public string CurrentUser { get; set; }
        public string GasL { get; set; }
        public Nullable<int> islimit { get; set; }
        public string SimId { get; set; }
        public string Site { get; set; }
        public string MtMile { get; set; }
        public string MtMileOrDate { get; set; }
    }
}
