//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManageSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cmsdbEntities : DbContext
    {
        public cmsdbEntities()
            : base("name=cmsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<associatecardinfo> associatecardinfo { get; set; }
        public DbSet<carcostregister> carcostregister { get; set; }
        public DbSet<carinfo> carinfo { get; set; }
        public DbSet<carlist> carlist { get; set; }
        public DbSet<departmentmanage> departmentmanage { get; set; }
        public DbSet<holidaydata> holidaydata { get; set; }
        public DbSet<illegalstatistic> illegalstatistic { get; set; }
        public DbSet<illegalusecar> illegalusecar { get; set; }
        public DbSet<limitcarnumber> limitcarnumber { get; set; }
        public DbSet<mainfuelingcard> mainfuelingcard { get; set; }
        public DbSet<msg_expire> msg_expire { get; set; }
        public DbSet<msg_maintain> msg_maintain { get; set; }
        public DbSet<msg_outreturncar> msg_outreturncar { get; set; }
        public DbSet<returnregister> returnregister { get; set; }
        public DbSet<trajectorylog> trajectorylog { get; set; }
        public DbSet<appversion> appversion { get; set; }
        public DbSet<jijian> jijian { get; set; }
        public DbSet<borrowregister> borrowregister { get; set; }
        public DbSet<msg_borrowcar> msg_borrowcar { get; set; }
        public DbSet<msg_userapply> msg_userapply { get; set; }
        public DbSet<user> user { get; set; }
    }
}
