//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManageSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg_outreturncar
    {
        public string Id { get; set; }
        public Nullable<int> IsLook { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Car { get; set; }
        public string Place { get; set; }
        public Nullable<int> DIsLook { get; set; }
        public Nullable<int> CarDepartment { get; set; }
        public Nullable<int> redpoint { get; set; }
        public Nullable<int> Dredpoint { get; set; }
    }
}
