//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManageSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string Account { get; set; }
        public string Password { get; set; }
        public string RealName { get; set; }
        public Nullable<int> Department { get; set; }
        public string AllowModel { get; set; }
        public Nullable<int> DriverType { get; set; }
        public string Email { get; set; }
        public string UserPhoto { get; set; }
        public string DriverLicensePhoto { get; set; }
        public Nullable<int> UserType { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> EffecDateStart { get; set; }
        public Nullable<System.DateTime> EffecDateEnd { get; set; }
        public string LastLoginDate { get; set; }
        public Nullable<int> ApplyRole { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<int> ApplyLevel { get; set; }
        public Nullable<int> ApplyState { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> Enable { get; set; }
        public string NotifySet { get; set; }
        public Nullable<int> Regulation { get; set; }
        public string DeviceID { get; set; }
    }
}
